import type { FreelancerProfile, JobPosting } from './types';

export const freelancers: FreelancerProfile[] = [
  {
    id: '1',
    name: 'Aarav Sharma',
    title: 'Senior Frontend Developer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Figma'],
    bio: 'A passionate frontend developer with over 8 years of experience building beautiful and performant web applications. I turn complex problems into simple, elegant solutions.',
    workHistory: 'Lead Developer at TechCorp (2018-2023), developed a large-scale e-commerce platform. Frontend Engineer at WebSolutions (2015-2018), worked on various client websites.',
    jobPreferences: 'Interested in remote frontend roles, particularly in the SaaS and e-commerce sectors. Prefers working with modern tech stacks like React and Next.js.',
    rate: 90,
    videoResumeUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  },
  {
    id: '2',
    name: 'Priya Patel',
    title: 'Full-Stack Engineer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Node.js', 'Python', 'React', 'PostgreSQL', 'Docker', 'AWS'],
    bio: 'Versatile full-stack engineer with a knack for building robust backend systems and interactive user interfaces. I enjoy tackling challenges across the entire stack.',
    workHistory: 'Full-Stack Engineer at Innovate Ltd. (2019-Present), building and maintaining microservices. Software Developer at DataDriven Inc. (2017-2019), focused on data processing pipelines.',
    jobPreferences: 'Looking for full-stack or backend-focused roles in startups or mid-sized tech companies. Open to projects involving cloud infrastructure and DevOps.',
    rate: 95,
  },
  {
    id: '3',
    name: 'Rohan Mehta',
    title: 'UI/UX Designer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
    bio: 'Creative and user-centric UI/UX designer dedicated to crafting intuitive and engaging digital experiences. I bridge the gap between user needs and business goals.',
    workHistory: 'Senior UX Designer at DesignHub (2020-2023), led design on mobile apps. UI Designer at Creative Agency (2018-2020), designed marketing websites and brand identities.',
    jobPreferences: 'Seeking UI/UX design roles that involve user research and product strategy. Excited about working on mobile apps and complex web applications.',
    rate: 80,
    videoResumeUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: '4',
    name: 'Anjali Gupta',
    title: 'DevOps & Cloud Architect',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Python', 'Go'],
    bio: 'Experienced DevOps engineer specializing in cloud architecture and automation. I help teams build scalable, reliable, and secure infrastructure.',
    workHistory: 'Cloud Architect at CloudNine (2017-Present), designed and implemented multi-cloud strategies. DevOps Engineer at ScaleUp (2014-2017), automated deployment pipelines.',
    jobPreferences: 'Roles focused on cloud infrastructure, site reliability engineering (SRE), or DevOps leadership. Interested in companies that are scaling their operations.',
    rate: 110,
  },
  {
    id: '5',
    name: 'Vikram Singh',
    title: 'Mobile Developer (iOS & Android)',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Swift', 'Kotlin', 'React Native', 'Firebase'],
    bio: 'Dedicated mobile developer focused on creating smooth, user-friendly applications for both iOS and Android platforms.',
    workHistory: 'Lead Mobile Developer at AppMakers (2019-Present). Junior Developer at MobileFirst (2017-2019).',
    jobPreferences: 'Looking for challenging mobile projects that push the boundaries of user experience.',
    rate: 100,
  },
  {
    id: '6',
    name: 'Sneha Reddy',
    title: 'Data Scientist',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Python', 'Pandas', 'scikit-learn', 'TensorFlow', 'SQL'],
    bio: 'Data scientist with a passion for uncovering insights from complex datasets and building predictive models.',
    workHistory: 'Data Scientist at Insights Corp (2018-Present). Data Analyst at Numbers Co (2016-2018).',
    jobPreferences: 'Roles in machine learning, predictive analytics, and natural language processing.',
    rate: 120,
  },
   {
    id: '7',
    name: 'Arjun Kumar',
    title: 'Cybersecurity Analyst',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Penetration Testing', 'SIEM', 'Network Security', 'Python'],
    bio: 'Proactive cybersecurity analyst with experience in threat detection and incident response.',
    workHistory: 'Security Analyst at SecureNet (2020-Present). IT Support at Global Tech (2018-2020).',
    jobPreferences: 'Seeking roles in a Security Operations Center (SOC) or in ethical hacking.',
    rate: 85,
  },
  {
    id: '8',
    name: 'Diya Sharma',
    title: 'Content Writer & SEO Specialist',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['SEO', 'Content Strategy', 'Copywriting', 'Google Analytics'],
    bio: 'Creative writer and SEO strategist who crafts compelling content that ranks.',
    workHistory: 'Content Lead at RankWell (2019-Present). Marketing Intern at Digitalify (2018-2019).',
    jobPreferences: 'Content marketing roles in the tech or B2B space.',
    rate: 60,
  },
];

export const jobs: JobPosting[] = [
  {
    id: '101',
    title: 'React Native Developer for Mobile App',
    company: 'MobileFirst Inc.',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We are looking for an experienced React Native developer to help us build the next generation of our flagship mobile application. You will be responsible for developing new features, improving performance, and ensuring a high-quality user experience.',
    requiredSkills: ['React Native', 'TypeScript', 'Redux', 'REST APIs'],
    budget: 10000,
  },
  {
    id: '102',
    title: 'Backend Engineer (Node.js/GraphQL)',
    company: 'DataStream Corp.',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Join our backend team to build and maintain our GraphQL API that powers our data analytics platform. You should have strong experience with Node.js, GraphQL, and database design.',
    requiredSkills: ['Node.js', 'GraphQL', 'PostgreSQL', 'Microservices'],
    budget: 12000,
  },
  {
    id: '103',
    title: 'Lead Product Designer',
    company: 'Userly',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Userly is seeking a Lead Product Designer to own the user experience for our suite of productivity tools. You will conduct user research, create wireframes and prototypes, and work closely with engineers to ship beautiful products.',
    requiredSkills: ['Figma', 'User Research', 'Prototyping', 'UX Strategy'],
    budget: 15000,
  },
  {
    id: '104',
    title: 'Cloud Security Engineer',
    company: 'SecureCloud',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We need a security-focused engineer to help us secure our AWS infrastructure. Responsibilities include vulnerability scanning, identity and access management, and implementing security best practices.',
    requiredSkills: ['AWS', 'Security', 'Terraform', 'CI/CD'],
    budget: 14000,
  },
  {
    id: '105',
    title: 'Frontend Developer (Vue.js)',
    company: 'FutureTech',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We are looking for a skilled Vue.js developer to join our frontend team. You will be working on our customer-facing dashboard, building new features and improving existing ones.',
    requiredSkills: ['Vue.js', 'Vuex', 'JavaScript', 'CSS'],
    budget: 9000,
  },
  {
    id: '106',
    title: 'Senior Python Developer',
    company: 'AutomateIt',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Seeking a senior Python developer to work on our automation platform. Experience with Django, Celery, and Redis is highly desirable.',
    requiredSkills: ['Python', 'Django', 'Celery', 'Redis'],
    budget: 13000,
  },
  {
    id: '107',
    title: 'Digital Marketing Manager',
    company: 'GrowthHackers',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We are looking for a data-driven Digital Marketing Manager to lead our user acquisition efforts across all digital channels.',
    requiredSkills: ['Google Ads', 'Facebook Ads', 'SEO', 'Email Marketing'],
    budget: 11000,
  },
  {
    id: '108',
    title: 'QA Automation Engineer',
    company: 'BugFree Ltd.',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Join our quality assurance team to build and maintain our automated testing frameworks. Experience with Selenium or Cypress is a must.',
    requiredSkills: ['Selenium', 'Cypress', 'JavaScript', 'CI/CD'],
    budget: 9500,
  },
];
