import type { FreelancerProfile, JobPosting } from './types';

export const freelancers: FreelancerProfile[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    title: 'Senior Frontend Developer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Figma'],
    bio: 'A passionate frontend developer with over 8 years of experience building beautiful and performant web applications. I turn complex problems into simple, elegant solutions.',
    workHistory: 'Lead Developer at TechCorp (2018-2023), developed a large-scale e-commerce platform. Frontend Engineer at WebSolutions (2015-2018), worked on various client websites.',
    jobPreferences: 'Interested in remote frontend roles, particularly in the SaaS and e-commerce sectors. Prefers working with modern tech stacks like React and Next.js.',
    rate: 90,
  },
  {
    id: '2',
    name: 'Bob Williams',
    title: 'Full-Stack Engineer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Node.js', 'Python', 'React', 'PostgreSQL', 'Docker', 'AWS'],
    bio: 'Versatile full-stack engineer with a knack for building robust backend systems and interactive user interfaces. I enjoy tackling challenges across the entire stack.',
    workHistory: 'Full-Stack Engineer at Innovate Ltd. (2019-Present), building and maintaining microservices. Software Developer at DataDriven Inc. (2017-2019), focused on data processing pipelines.',
    jobPreferences: 'Looking for full-stack or backend-focused roles in startups or mid-sized tech companies. Open to projects involving cloud infrastructure and DevOps.',
    rate: 95,
  },
  {
    id: '3',
    name: 'Charlie Brown',
    title: 'UI/UX Designer',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
    bio: 'Creative and user-centric UI/UX designer dedicated to crafting intuitive and engaging digital experiences. I bridge the gap between user needs and business goals.',
    workHistory: 'Senior UX Designer at DesignHub (2020-2023), led design on mobile apps. UI Designer at Creative Agency (2018-2020), designed marketing websites and brand identities.',
    jobPreferences: 'Seeking UI/UX design roles that involve user research and product strategy. Excited about working on mobile apps and complex web applications.',
    rate: 80,
  },
  {
    id: '4',
    name: 'Diana Prince',
    title: 'DevOps & Cloud Architect',
    avatarUrl: 'https://placehold.co/128x128.png',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Python', 'Go'],
    bio: 'Experienced DevOps engineer specializing in cloud architecture and automation. I help teams build scalable, reliable, and secure infrastructure.',
    workHistory: 'Cloud Architect at CloudNine (2017-Present), designed and implemented multi-cloud strategies. DevOps Engineer at ScaleUp (2014-2017), automated deployment pipelines.',
    jobPreferences: 'Roles focused on cloud infrastructure, site reliability engineering (SRE), or DevOps leadership. Interested in companies that are scaling their operations.',
    rate: 110,
  },
];

export const jobs: JobPosting[] = [
  {
    id: '101',
    title: 'React Native Developer for Mobile App',
    company: 'MobileFirst Inc.',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We are looking for an experienced React Native developer to help us build the next generation of our flagship mobile application. You will be responsible for developing new features, improving performance, and ensuring a high-quality user experience.',
    requiredSkills: ['React Native', 'TypeScript', 'Redux', 'REST APIs'],
    budget: 10000,
  },
  {
    id: '102',
    title: 'Backend Engineer (Node.js/GraphQL)',
    company: 'DataStream Corp.',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Join our backend team to build and maintain our GraphQL API that powers our data analytics platform. You should have strong experience with Node.js, GraphQL, and database design.',
    requiredSkills: ['Node.js', 'GraphQL', 'PostgreSQL', 'Microservices'],
    budget: 12000,
  },
  {
    id: '103',
    title: 'Lead Product Designer',
    company: 'Userly',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'Userly is seeking a Lead Product Designer to own the user experience for our suite of productivity tools. You will conduct user research, create wireframes and prototypes, and work closely with engineers to ship beautiful products.',
    requiredSkills: ['Figma', 'User Research', 'Prototyping', 'UX Strategy'],
    budget: 15000,
  },
  {
    id: '104',
    title: 'Cloud Security Engineer',
    company: 'SecureCloud',
    logoUrl: 'https://placehold.co/128x128.png',
    description: 'We need a security-focused engineer to help us secure our AWS infrastructure. Responsibilities include vulnerability scanning, identity and access management, and implementing security best practices.',
    requiredSkills: ['AWS', 'Security', 'Terraform', 'CI/CD'],
    budget: 14000,
  },
];
